version: '3'
networks:
  my_app_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
          gateway: 172.28.0.1
services:
  my-app-sql:
    build:
      context: ./my-app-sql
    ports: 
      - 3306:3306
    networks:
      - my_app_network
    volumes:
      - ./my-app-sql-data/data:/var/lib/mysql
  my-app-api:
    build:
      context: ./my-app-api
    ports: 
      - 3030:3030
    networks:
      - my_app_network
    depends_on:
      - my-app-sql
  my-app-api-search:
    build:
      context: ./my-app-api-search
    ports: 
      - 3131:3131
    networks:
      - my_app_network
    depends_on:
      - my-app-sql
  my-app-front:
    build:
      context: ./my-app-front
    ports:
      - 3000:3000
    networks:
      - my_app_network
    environment:
      - NEXT_PUBLIC_BACKEND_API=http://my-app-api:3030
      - NEXT_PUBLIC_BACKEND_API_2=http://localhost:3131
    depends_on:
      - my-app-sql
      - my-app-api
  my-app-redis:
    build:
      context: ./my-app-redis
    ports:
      - 6379:6379
    networks:
      - my_app_network
    environment:
      - REDIS_PASSWORD=root
volumes: 
  my-app-sql-data: