version: '3'
networks:
  my_app_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
          gateway: 172.28.0.1
services:
  my-app-sql:
    build:
      context: ./my-app-sql
    ports: 
      - 3306:3306
    networks:
      - my_app_network
  my-app-api:
    build:
      context: ./my-app-api
    ports: 
      - 3030:3030
    networks:
      - my_app_network
    depends_on:
      - my-app-sql
  my-app-front:
    build:
      context: ./my-app-front
    ports:
      - 3000:3000
    networks:
      - my_app_network
    depends_on:
      - my-app-sql
      - my-app-api
